services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@flask_db:5432/${POSTGRES_DB}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - WEATHER_POST_PASSWORD=${WEATHER_POST_PASSWORD}
      - REDIS_URL=redis://flask_redis:6379/0
    depends_on:
      - flask_db
      - flask_redis

  flask_db:
    container_name: flask_db
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_redis:
    container_name: flask_redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
