version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://q9JH2exxJSZT135JFo6i:F20lJ92mSDGqMy0URufq@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=F20lJ92mSDGqMy0URufq
      - POSTGRES_USER=q9JH2exxJSZT135JFo6i
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
