"""restore table

Revision ID: 122082bb2250
Revises: 8819b838c9a3
Create Date: 2024-06-30 23:55:49.376747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122082bb2250'
down_revision = '8819b838c9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='media_reviews_schema'
    )
    op.create_table('media_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('review_creation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('review_last_update_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('media_creation_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consumed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='media_reviews_schema'
    )
    op.create_table('media_review_genre',
    sa.Column('media_review_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['media_reviews_schema.genres.id'], ),
    sa.ForeignKeyConstraint(['media_review_id'], ['media_reviews_schema.media_reviews.id'], ),
    sa.PrimaryKeyConstraint('media_review_id', 'genre_id'),
    schema='media_reviews_schema'
    )
    op.create_table('sub_media_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_review_id', sa.Integer(), nullable=False),
    sa.Column('display_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('review_creation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('review_last_update_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('media_creation_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consumed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['media_review_id'], ['media_reviews_schema.media_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media_reviews_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_media_reviews', schema='media_reviews_schema')
    op.drop_table('media_review_genre', schema='media_reviews_schema')
    op.drop_table('media_reviews', schema='media_reviews_schema')
    op.drop_table('genres', schema='media_reviews_schema')
    # ### end Alembic commands ###
