"""unique index constraint to subreview

Revision ID: 45d419fb7764
Revises: 6a9fb3c06253
Create Date: 2024-06-30 17:55:00.020811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d419fb7764'
down_revision = '6a9fb3c06253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.add_column(sa.Column('display_index', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_media_review_sub_review_index', ['media_review_id', 'display_index'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.drop_constraint('uq_media_review_sub_review_index', type_='unique')
        batch_op.drop_column('display_index')

    # ### end Alembic commands ###
