"""Added subreview

Revision ID: 6a9fb3c06253
Revises: 
Create Date: 2024-06-30 17:45:34.053240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9fb3c06253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_media_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_review_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('review_creation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('review_last_update_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('media_creation_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consumed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['media_review_id'], ['media_reviews_schema.media_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media_reviews_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_media_reviews', schema='media_reviews_schema')
    # ### end Alembic commands ###
