"""removed subreview constraint

Revision ID: 8819b838c9a3
Revises: f8a5b577b022
Create Date: 2024-06-30 21:39:37.305282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8819b838c9a3'
down_revision = 'f8a5b577b022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.drop_constraint('uq_media_review_sub_review_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.create_unique_constraint('uq_media_review_sub_review_name', ['media_review_id', 'name'])

    # ### end Alembic commands ###
