"""Initial migration.

Revision ID: cfcd8ffd1b10
Revises: 
Create Date: 2024-06-30 14:31:02.067528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfcd8ffd1b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='media_reviews_schema'
    )
    op.create_table('media_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('review_creation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('review_last_update_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('media_creation_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consumed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='media_reviews_schema'
    )
    op.create_table('media_review_genre',
    sa.Column('media_review_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['media_reviews_schema.genres.id'], ),
    sa.ForeignKeyConstraint(['media_review_id'], ['media_reviews_schema.media_reviews.id'], ),
    sa.PrimaryKeyConstraint('media_review_id', 'genre_id'),
    schema='media_reviews_schema'
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index('sensor_data_timestamp_idx')

    op.drop_table('sensor_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ambient_light', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('air_quality_index', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tvoc', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('eco2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('air_quality_index >= 1 AND air_quality_index <= 5', name='sensor_data_air_quality_index_check')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index('sensor_data_timestamp_idx', [sa.text('timestamp DESC')], unique=False)

    op.drop_table('media_review_genre', schema='media_reviews_schema')
    op.drop_table('media_reviews', schema='media_reviews_schema')
    op.drop_table('genres', schema='media_reviews_schema')
    # ### end Alembic commands ###
