"""pros and cons no longer nullable

Revision ID: d5278085e62d
Revises: 122082bb2250
Create Date: 2024-07-01 19:26:05.338496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5278085e62d'
down_revision = '122082bb2250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.alter_column('pros',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
        batch_op.alter_column('cons',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.alter_column('pros',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
        batch_op.alter_column('cons',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.alter_column('cons',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.alter_column('pros',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)

    with op.batch_alter_table('media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.alter_column('cons',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.alter_column('pros',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)

    # ### end Alembic commands ###
