"""Updated subreview constraint

Revision ID: f8a5b577b022
Revises: 45d419fb7764
Create Date: 2024-06-30 20:11:17.999744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a5b577b022'
down_revision = '45d419fb7764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.drop_constraint('uq_media_review_sub_review_index', type_='unique')
        batch_op.create_unique_constraint('uq_media_review_sub_review_name', ['media_review_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_media_reviews', schema='media_reviews_schema') as batch_op:
        batch_op.drop_constraint('uq_media_review_sub_review_name', type_='unique')
        batch_op.create_unique_constraint('uq_media_review_sub_review_index', ['media_review_id', 'display_index'])

    # ### end Alembic commands ###
